### ISSUE TITLE
Hugo 0.120 deprecations (not broken yet)

### ISSUE THREAD

**Issue by scivision** [ldeso/hugo-flex#30]
Hugo 0.120 just released made a couple deprecations that are a trivial find and replace to upgrade. 
Specifically, site.author.email and site.author.name. They still work in Hugo 0.120 but are now deprecated. 

https://github.com/gohugoio/hugo/releases/tag/v0.120.0

**Comment by ldeso** [comment]
Thanks for letting me know. This should do the trick.
