### ISSUE TITLE
Language code

### ISSUE THREAD

**Issue by ashtallama** [ldeso/hugo-flex#32]
In your baseof.html

```
<html{{ with site.LanguageCode | default site.Language.Lang }} lang="{{ . }}"{{ end }}>
```

Could work better if replaced with this instead

```
<html lang="{{ or site.LanguageCode site.Language.Lang }}">
```
which is the standard way to define the language code in Hugo.

**Comment by ldeso** [comment]
Thanks a lot for your interest! You are right, the code I use in my baseof.html was from the [official template](https://github.com/gohugoio/hugo/blob/v0.112.5/tpl/tplimpl/embedded/templates/alias.html#L2) which was changed up from [Hugo v0.112.6](https://github.com/gohugoio/hugo/blob/v0.112.6/tpl/tplimpl/embedded/templates/alias.html). I'm going to update it.
