### ISSUE TITLE
Can’t mix math and Markdown in the same paragraph

### ISSUE THREAD

**Issue by sboukortt** [ldeso/hugo-flex#36]
It seems that it’s currently not possible to mix Markdown and inline math in the same paragraph:

- ```
  {{<math>}}Here is [a link](https://github.com/ldeso/hugo-flex). By the way, $1 + 1 = 2$.{{</math>}}
  ```
  would cause the link not to be rendered.

  (Replacing this line: https://github.com/ldeso/hugo-flex/blob/16a8dac9bba9eb68a849ec9d5e36e0d472f54b0e/layouts/shortcodes/math.html#L19 with `{{ .Inner | markdownify }}` would solve this, and would let one just wrap an entire article in `{{<math>}}`.)

- ```
  Here is [a link](https://github.com/ldeso/hugo-flex). By the way, {{<math>}}$1 + 1 = 2${{</math>}}.
  ```

  renders the link and the math but the math is displayed in its own block since it gets put in a `<div>`. (And having to intersperse an entire article with these would not be ideal.)

Or perhaps I am missing something?

Thanks.

**Comment by ldeso** [comment]
Thanks a lot! This is fixed in [v1.0.4](https://github.com/ldeso/hugo-flex/releases/tag/v1.0.4).
