### ISSUE TITLE
CSS File Name Length

### ISSUE THREAD

**Issue by AncientMecha** [ldeso/hugo-flex#38]
Hello! I'm encountering an issue where the filename for one of the CSS files in ./public/css is too long for my hosting provider to support.

I've spent a couple hours digging through the files, but I am basically unskilled at webdev, so I can't figure out how to generate a smaller file name. 

My best guess is that it looks like maybe it's generating a hash and putting it in the file name to compare to a key? I just don't have enough understanding yo even find where this process is happening, much less bypass it for a smaller file name.

I'm guessing you put that process in there for a reason, but could you advise me on how to make this change on my end? I don't think my casual little blog really warrants verifying the integrity of my CSS file before loading it.

Thank you, have a great day!

**Comment by ldeso** [comment]
Hello, thanks for this bug report! The issue should be fixed in [v1.2.1](https://github.com/ldeso/hugo-flex/releases/tag/v1.2.1). If the file names are still too long for your hosting provider, let me know and I will try to reduce them further.

**Comment by AncientMecha** [comment]
Oh, thank you! And thanks for the tip I'll build with those flags until the next release!

Have a great weekend!

**Comment by ldeso** [comment]
No worries!

Note that with the Hugo Flex theme, setting the environment to "development" also disables adding `crossorigin="anonymous"` to links to CSS and JS resources (I copied [this behavior](https://github.com/gohugoio/hugo/blob/v0.128.0/create/skeletons/theme/layouts/partials/head/css.html) from the basic theme that is [shipped with hugo](https://gohugo.io/commands/hugo_new_theme/)). If that is a problem for you, I recommend to update the theme to the latest version ([v1.2.2](https://github.com/ldeso/hugo-flex/releases/tag/v1.2.2)) and not to set this flag in production. :slightly_smiling_face:
